# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
cover: 

title: Cyber
description: 

# Build settings
markdown: kramdown
highlighter: null

# Handling Reading
exclude: ["README.md", "LICENSE"]

# User's info
fullname: sdfsfsdfsdfsdfdsfsdfsdfsdfsdfsdfsdfds
email: 
twitter: 
github: 
youtube: 
google: 
facebook: 

# Articles categories
sets:
    - title: 
      description:

# SEO
keywords:
    - javascript
    - js
    - php
    - css
    - laravel
    - angular
    - angularjs
    - life
    - programming
    - spa
    - single page application
    - api
    - maroc
    - morocco
