# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://electrik-frog.com" # the base hostname & protocol for your site

title: Electrik Frog
description: My journey twoard becoming a better developer.
# Build settings
markdown: kramdown
highlighter: null

# Handling Reading
exclude: ["README.md", "LICENSE"]

# User's info
fullname: Motaquillah Maddane
email: mailto:maddane.info@gmail.com
twitter: https://twitter.com/electrik_frog
github: https://github.com/kronik3r
youtube: https://www.youtube.com/channel/UC0vUE2Im9VBRupZ_huV-9kg
google: https://plus.google.com/+MotaquillahMaddane
facebook: https://www.facebook.com/electrik.frog

# Articles categories
sets:
    - title: This Developer Life
      description: My stories twoard becoming a better developer and also trying to unlock the secrets of the univers
      id: this-life

# SEO
keywords:
    - javascript
    - js
    - php
    - css
    - laravel
    - angular
    - angularjs
    - life
    - programming
    - spa
    - single page application
    - api
    - maroc
    - morocco